### ISSUE TITLE
Vue-only compatible

### ISSUE THREAD

**Issue by tanc** [cereschen/vite-plugin-svg-sprite-component#1]
Hi, was trying out your plugin but it wants to import Vue which my project doesn't need. Is it possible to update the README to make this clear for the next person trying your plugin? Thanks!

**Comment by cereschen** [comment]
> Hi, was trying out your plugin but it wants to import Vue which my project doesn't need. Is it possible to update the README to make this clear for the next person trying your plugin? Thanks!

@tanc  Now, the plugin no longer just for Vue,please try 1.0.5

**Comment by tanc** [comment]
@cereschen thanks I can confirm it works without Vue! I did have to change the way the icon is referenced as `xlink:href` was not working in the browser I tested. I [read that the standard](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) is now to use `href` directly like so:

```
<svg>
  <use href="#icon-youtube" />
</svg>
```

Thanks again!
