### ISSUE TITLE
How to import multiple svg files?

### ISSUE THREAD

**Issue by liho00** [cereschen/vite-plugin-svg-sprite-component#4]
Can we make it simple like just import the parent directory, and all its svg inside the particular directory will be compiled and inserted into the dom

**Comment by cereschen** [comment]
Yes, it can be done
https://vitejs.dev/guide/features.html#glob-import

**Comment by liho00** [comment]
> Yes, it can be done
> https://vitejs.dev/guide/features.html#glob-import

yeah, its works, but i faced another issue, i will closed this and open a new issue.

**Comment by liho00** [comment]
> Yes, it can be done
> https://vitejs.dev/guide/features.html#glob-import

Thanks its work, but i face another issue, i will open a new issue.
