### ISSUE TITLE
Sprite format

### ISSUE THREAD

**Issue by liho00** [cereschen/vite-plugin-svg-sprite-component#6]
Current behavior
![image](https://user-images.githubusercontent.com/77238199/113678390-27908700-96f1-11eb-99b8-ffe0f30fc7f5.png)

Expected behavior
![image](https://user-images.githubusercontent.com/77238199/113677891-a507c780-96f0-11eb-85ae-96686036849e.png)

I suggest to use symbol to represent each of the svg file, instead of insert full svg into the div, if i have 100 icons, it might reduce the performance of the dom, besides i think the format shown at above screenshot is quite clean and efficient.

**Comment by cereschen** [comment]
Upgrade 1.0.7, and that should be what you want

**Comment by liho00** [comment]
Thanks, i tried 1.0.7, it working well. Appreciated!
