### ISSUE TITLE
Sourcemap is likely to be incorrect

### ISSUE THREAD

**Issue by floydback** [cereschen/vite-plugin-svg-sprite-component#9]
When I run `yarn build` with enabled **sourcemap** attribute I've get error:

> Sourcemap is likely to be incorrect: a plugin (svg-sprite-component) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

**Comment by cereschen** [comment]
This may be the latest version of vite, but do we need the sourcemap of the svg  files? But this tip is annoying. I'll consider doing it.

**Comment by floydback** [comment]
The problem is Vite doesn’t generate sources at all while using plugin svg sprite.

**Comment by liho98** [comment]
Yup same issues, its throwing some error messages, it will causes my CI build failed. Feel free to check this out @cereschen Thanks in advance!
![image](https://user-images.githubusercontent.com/44250267/130568132-e8ec9e6e-3f04-4927-98a0-588aa68b281f.png)

**Comment by cereschen** [comment]
@liho98 I can't even reproduce this problem, but I have dealt with the sourmap problem, please update 1.0.9

**Comment by liho98** [comment]
> @liho98 I can't even reproduce this problem, but I have dealt with the sourmap problem, please update 1.0.9

Try with v1.0.9, the issue still persists, you may reproduce this error by enable the sourcemap when build.

```
// vite.config.js
    build: {
      sourcemap: true,
    },
```

**Comment by cereschen** [comment]
> > @liho98 I can't even reproduce this problem, but I have dealt with the sourmap problem, please update 1.0.9
> 
> Try with v1.0.9, the issue still persists, you may reproduce this error by enable the sourcemap when build.
> 
> ```
> // vite.config.js
>     build: {
>       sourcemap: true,
>     },
> ```

You only need to upgrade 1.0.10. I have passed the test

**Comment by liho00** [comment]
> > > @liho98 I can't even reproduce this problem, but I have dealt with the sourmap problem, please update 1.0.9
> > 
> > 
> > Try with v1.0.9, the issue still persists, you may reproduce this error by enable the sourcemap when build.
> > ```
> > // vite.config.js
> >     build: {
> >       sourcemap: true,
> >     },
> > ```
> 
> You only need to upgrade 1.0.10. I have passed the test

yup tested, did not throwing the error messages already, thanks!
